### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by cicero-reis** [cicero-reis/github-action#1]
I think it looks better if the main title is a bit more change

The styling rule could be changed like this:

 ```css
h1 {
 color: #efa82e
}
```
